
version: "3.4"
services:
  web:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

